name: Build and Deploy LaTeX

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex 

    - name: Rename PDF
      run: mv main.pdf Owen-Fahey-Resume.pdf  # Rename the PDF file to Owen.pdf

    - name: Prepare files for deployment
      run: |
        mkdir pdf_output
        cp Owen-Fahey-Resume.pdf pdf_output/  # Copy Owen.pdf to this new directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./pdf_output 
